name: Deploy Static Content to Pages

on:
  push:
    branches: ["main"] # 当 main 分支有变动时触发
  workflow_dispatch:   # 允许手动触发

# 设置权限以允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # 部署根目录下的所有文件
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4